_target_: src.models.isic_module.ISICLitModule

name: efficientnetv2_l
backbone: tf_efficientnetv2_l.in21k_ft_in1k
num_classes: 1
pretrained: true
lr: 0.00005
weight_decay: 0.01
max_epochs: ${trainer.max_epochs}
dropout: 0.3
pos_weight: 1.0  # overridden at runtime from training data class ratio
