_target_: src.models.isic_module.ISICLitModule

name: eva02_large
backbone: eva02_large_patch14_448.mim_in22k_ft_in1k
num_classes: 1
pretrained: true
lr: 0.00003
weight_decay: 0.05
max_epochs: ${trainer.max_epochs}
dropout: 0.3
