# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.WandbLogger
  name: "${experiment_name}"
  project: "isic-2024"
  save_dir: "${paths.output_dir}"
  offline: False
  id: null # pass correct id to resume experiment!
  anonymous: null # options: [allow, must]
  log_model: "all" # upload checkpoint data to wandb
  prefix: ""
  group: ""
  tags: []
  job_type: ""