# Path to project root
work_dir: ${hydra:runtime.cwd}

# Path to data directory
data_dir: ${paths.work_dir}/data

# Path to output directory (for logs and checkpoints)
output_dir: ${paths.work_dir}/logs

# Path to checkpoints directory
ckpt_dir: ${paths.output_dir}/checkpoints

log_dir: ${paths.work_dir}/logs

# Hugging Face Hub repository for model checkpoints
hf_repo_id: "RudraShivm/skin-cancer-detection-isic2024"